### ISSUE TITLE
[Exception] Return value of Smajti1\Laravel\Wizard::dataStep() must be of the type array, string returned

### ISSUE THREAD

**Issue by StenKoning** [smajti1/laravel-wizard#1]
Return value of Smajti1\Laravel\Wizard::dataStep() must be of the type array, string returned

In my case dataStep returns a single value. I have another question, I would like to save the progress of the wizard in the database. How would you do that?

**Comment by ycs77** [comment]
Are you still concerned about this issue?
In fact, there is a new package [ycs77/laravel-wizard](https://github.com/ycs77/laravel-wizard) that solves this problem.
It also provides the ability to save progress to database. (set `driver` to "database" from `config/wizard.php` )
