### ISSUE TITLE
Laravel 8.x support

### ISSUE THREAD

**Issue by nevedimko** [smajti1/laravel-wizard#5]
Hello @smajti1 and thanks for you work. 
Do you plan to add Laravel 8.x support?

**Comment by nevedimko** [comment]
I've opened a PR #6

**Comment by smajti1** [comment]
Hello @nevedimko thanks for using my library.
I will try update this library probably at the end of week you should have new version :).
And thanks for pull request i miss there some info in `README.md` and `CHANGELOG.md` and i will add it

**Comment by smajti1** [comment]
Hey @nevedimko I already pushed new release https://github.com/smajti1/laravel-wizard/releases/tag/v1.5.0 and you can test it :)

**Comment by nevedimko** [comment]
@smajti1 Thank you! I switched project to new version and it works perfectly.
